---
- hosts: all
  tasks:
    - name: 'Instala o pacote do php' 
      apt:
        name: php5                    
        state: latest                
      become: yes     
    - name: 'Instala o pacote do Apache2'
      apt:
        name: apache2
        state: latest
      become: yes  
    - name: 'Instalando o modphp'
      apt:
        name: libapache2-mod-php5
        state: latest
      become: yes                      